language: cpp
dist: xenial
compiler: gcc

# Boost
addons: 
  apt: 
    packages: libboost-all-dev

install: 
  # Qt5
  - sudo apt install qt5-default
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh

script: 
  # Build test
  - qmake -qt=qt5 travis_qmake_gcc_cpp14_boost_test_gcov_oclint_qt5_test.pro
  - make --silent
  # Build 'real' program
  - qmake -qt=qt5 travis_qmake_gcc_cpp14_boost_test_gcov_oclint_qt5.pro
  - make --silent
  # Run tests
  - ./travis_qmake_gcc_cpp14_boost_test_gcov_oclint_qt5_test
  # Get code coverage
  - ./get_code_cov.sh
  - codecov
  # Call OCLint
  - ./do_oclint.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)